### ISSUE TITLE
Settings menu on start up

### ISSUE THREAD

**Issue by Atresia** [lemasatodev/POE-Trades-Companion#1]
Can you please disable that the settings menu pops up on the initial start of the program?

**Comment by lemasatodev** [comment]
This was due to the debug file being enabled by default, which it shouldn't have
Thanks :)

**Comment by lemasatodev** [comment]
If you are still having this issue after updating, delete the Debug.json file in your folder ; or start fresh by downloading the latest release at https://github.com/lemasatodev/POE-Trades-Companion/releases

Don't bother about the references below, those are related to the alpha branch
