### ISSUE TITLE
Kicking self is outdated

### ISSUE THREAD

**Issue by Edwards-R** [lemasatodev/POE-Trades-Companion#2]
Multiple places refer to `/kick %myself%` which relies on API calls and scraping etc etc. A _**much**_ better option is the POE built in `/leave` command which needs none of that. It removes a bunch of edge cases and problems.

**Comment by lemasatodev** [comment]
Correct, this API has been discontinued long
Updated the action to use /leave instead
	f22890d8ca5352cd217a2b68a3d4e4ac7b1a269a
	e9e4f29359e7a45fd583c2e365ca39584dc65072
Thanks :)
