### ISSUE TITLE
Trade statistics

### ISSUE THREAD

**Issue by Kofge** [lemasatodev/POE-Trades-Companion#4]
Is it possible to somehow delete all the statistics of trades that have accumulated over several years of play? I would like to start keeping it from the beginning.

**Comment by lemasatodev** [comment]
Deleting Sell_History.json and Buy_History.json in the following folder will suffice
%USERPROFILE%\Documents\lemasato\POE Trades Companion

**Comment by Kofge** [comment]
Thank you so much, uninstalled it and it cleared! Good luck
